# This is a basic workflow to help you get started with Actions

name: Beta Release

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the develop branch
on:
  push:
    branches:
      - develop
      
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  publish:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2        
    - uses: actions/setup-node@v1
      with:
        node-version: 10.19.0
    - name: Preparing environment
      id: setup
      run: npm install -g yarn
    - name: Installing modules
      id: modules
      run: |
        yarn install
    - name: Build
      id: build
      run: ./node_modules/.bin/tsc
    - name: Publish
      if: always()
      id: publish
      run: |
        ./node_modules/.bin/npm-cli-login -u ${{ secrets.NPM_USER }} -p '${{ secrets.NPM_PASSWORD }}' -e ${{ secrets.NPM_EMAIL }}
        npm publish --access public --tag beta
    - name: Slack notification
      uses: Foxhoundn/slack@v1.2.93
      with: 
        status: ${{ job.status }}
        steps: ${{ toJson(steps) }}
      if: always()
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_USERNAME: ReQore Publish
  release:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2        
    - uses: actions/setup-node@v1
      with:
        node-version: 10.19.0
    - name: Save release tag
      id: release_tag
      run: echo ::set-output name=version::$(node -pe "require('./package.json').version")
    - name: Create a release
      id: release
      uses: actions/create-release@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ steps.release_tag.outputs.version }}
        release_name: v${{ steps.release_tag.outputs.version }}
        body: v${{ steps.release_tag.outputs.version }}
        draft: false
        prerelease: false
    - name: Slack notification
      uses: Foxhoundn/slack@v1.2.93
      with: 
        status: ${{ job.status }}
        steps: ${{ toJson(steps) }}
      if: always()
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_USERNAME: ReQore Publish
